from dotenv import load_dotenv
from langgraph.graph import MessagesState
from langgraph.prebuilt import ToolNode
#for the toolcall from the Agent if tool is used using toolnode

from langchain_core.messages import SystemMessage

from react import tools, llm

load_dotenv()
# Create a LLM reasoning node

SYSTEM_MESSAGE = """You are a helpful assistant to provide answer only using the tools provided. 
If you don't know the answer, say you don't know."""

def run_agent_reasoning(state: MessagesState) -> MessagesState:
    """Function to run the agent with the given query to retrive content from the given documentation
    and generate a response based on the retrieved context.
    
    Args: query
    
    Returns:
      Dictionary contains:
        Answer: The answer generated by the agent based on the retrieved context.
        Context: The relevant context retrieved from the vector store."""
    
    system_prompt = SYSTEM_MESSAGE

    messages = state["messages"]
    response = llm.invoke([SystemMessage(content=system_prompt), *messages])
    #Build the messages for the agent, starting with the user's query. The agent will then use the retrieve_context tool to get relevant information from the vector store and generate a response based on that context.
    return {"messages": [response]}

tool_node = ToolNode(tools=tools)
#using the langgraph prebuilt tool node to create a node that can call the tools defined in the react.py file. This node will be used in the graph to allow the agent to call the tools when generating responses.



